### ISSUE TITLE
Other category always shows an error. 

### ISSUE THREAD

**Issue by Tim-Rapp** [dam5s/android-starter#1]
Nice work on the app Damien! +1 for kotlin. 

  https://api.icndb.com/jokes/ has no "other" category, joke category = "nerdy" or "explicit" or [] (empty array)

**Comment by dam5s** [comment]
Ha, thanks Tim. As you can see, I'm not particularly good at keeping track of issues. Just removed it to avoid confusion.

https://github.com/dam5s/android-starter/commit/657845a25dc41ba88edfee1778c4c88f59b3aa96
